#! /usr/local/bin/tcsh

# wraps a script to be executed by cron and sets up necessary environment
# for root.

# usage: cron_wrapper <working dir> <output file> <command> [<arg1> ... <argN>]

# read in arguments
setenv WORKING_DIR $1
setenv OUTPUT_FILE $2
shift
shift

# set root4star environment
setenv GROUP_DIR /afs/rhic.bnl.gov/rhstar/group 
setenv CERN_ROOT /cern/pro
setenv CERN      /cern
setenv HOME      /star/users/starlib
setenv SILENT    1

source /afs/rhic.bnl.gov/rhstar/group/.stardev
/usr/afsws/bin/klog -pa `cat /afs/rhic.bnl.gov/star/starqa/qa01/.cgi`

# change to working directory
cd $WORKING_DIR

# run program w/args
$argv >>& $OUTPUT_FILE


