#!/usr/bin/env perl

# Simple script to stat the files on the commandline, and return
# an error condition if they don't respond within 10 seconds, or
# if the file is not readable
#
# Reshaped from a script from sychan 4/9/2001 (PDSF)
# J. Lauret 2009
#

$TIMEOUT=10;

# return true if no argument
return 1 if $#ARGV == -1;

eval {
    # Set signal handler to call anon routine with "die" command
    $SIG{ALRM} = sub { die "stat on $filename Timed out"; };

    # For every file on the command line, try to stat it
    foreach $filename ( @ARGV) {
        alarm($TIMEOUT); # $TIMEOUT second timeout on the stat
        die "$filename not readable" unless ( -r $filename );
        alarm(0);        # reset timeout
    }
};

if ($@) {
    print "Error: $@";
    exit( 1);
} else {
    exit( 0 );
}
