#!/opt/star/bin/perl
#  $Id: dropit,v 1.3 2000/05/02 22:45:50 fisyak Exp $
#  $Log: dropit,v $
#  Revision 1.3  2000/05/02 22:45:50  fisyak
#  Replace shell version by perl one
#
#  Revision 1.2  1998/03/26 16:41:31  fisyak
#  Add STAR_LEVELS
#
#  Revision 1.1  1998/03/23 02:29:14  fisyak
#  Fix group start-up
#
#  Revision 1.2  1998/02/22 02:07:49  fisyak
#  use ftul parameter definitions
#
#  Revision 1.1  1998/02/17 18:06:47  fisyak
#  Add dropit for PATH
#
# dropit [-i input_delimiter] [-d output_delimiter] [-p string] [substring] 
#      DESCRIPTION
#          dropit's intended purpose is to remove program library names
#          from a PATH shell variable value, which has colon separated
#          fields.  dropit is usable in sh, ksh, and csh shell script
#          and source files.
#
#          If the -i option is not specified, the input separator is a
#          colon.  If the -d option is not specified, the output
#          separator is a colon.  If the -p option is not specified,
#          the value of the PATH shell environment variable is used.
#
#          Option value meanings are:
#
#             input_delimiter
#                       input separator
#
#             output_delimiter
#                       output separator
#
#             string    the string containing colon separated fields to
#                       be operated on
#
#             substring a string which if it is a substring of a field
#                       causes the field to be omitted
#
#
my $FS=":";
my $DS=":";
my $string= $ENV{PATH};# print "string $string\n";
my @substring=();
while ($#ARGV > -1) {
  my $test = shift @ARGV;# print "test $test\n";
  next if $test eq '-c';
  if ($test eq '-i') {$FS = shift @ARGV; next;}      
  if ($test eq '-d') {$DS = shift @ARGV; next;}     
  if ($test eq '-p') {$string = shift @ARGV;  next; } 
  if ($test =~ /^-/) {shift @ARGV; next;}           
  push @substring, $test;# print "substring = $substring\n";
}
my $ostring = $string;
my @words = split $FS, $string;
my @newwords = ();
# remove words containing substring
foreach my $word (@words) {
  foreach my $s (@substring) {if ($word =~ $s) {goto NEXT};}
  push @newwords, $word;
 NEXT:
}
# remove duplications
@words = ();
foreach my $word (@newwords) {# print "word = $word\n";
  foreach my $w (@words) {# print "word $word and w = $w\n";
			   goto LAST if $w eq $word;}
  push @words, $word;# print "add $word\n";
 LAST:
}
$string = join $DS,@words;
if ($string) {print "$string\n";}
else         {print "$ostring\n";}
