#!/bin/csh -f

#
# dropit.pl is dangerous because usage abuse of such statement
#  setenv XXX `dropit -p XXX ...`
#
# would lead to destroying variable XXX shall the internal test
# /usr/bin/env perl fail.
#
# If you modify the .pl script, please modify the csh as well !!
# chs script is "safe" i.e. all Uglix program are specified
# with full path but since there is a need for many back-ticked
# commands to accomplish the same than one line of perl, it is
# also slower.
#
#

set PTEST=`which perl`

if ("$PTEST" != "") then
    $PTEST $0.pl $*
else
    $0.csh $*
endif

