#!/bin/csh

#
# This csh extraneous wrapping is made because
# when dropit is called from within our login
# scripts (about everywhere), the path is no 
# necessarily defined OR the OS is new and do
# not have all the necessary software for our 
# login to function. 
#
# To avoid a dog-bitting-his-tail situation, we
# look for perl at expected possible places. We
# are saved by csh once again ...
#

set DIRS="/usr/bin /usr/local/bin /opt/star/bin /afs/rhic/opt/star/bin"

foreach tdir ($DIRS)
    if ( -e $tdir/perl ) then
      #echo "Found $tdir/perl"
      if ( ! $?PERL ) then
         set PERL=$tdir/perl
         break
      endif
   endif
end


if ( ! $?PERL ) then
  #echo "$0 cannot find perl anywhere"
  exit
else
  #echo $PERL $0.pl

  $PERL $0.pl $*

endif


