#!/bin/csh
#  $Log: STAR_SYS,v $
#  Revision 1.8  1999/01/08 20:08:27  fisyak
#  Remove call to fs fro rc[as/rs]
#
#  Revision 1.7  1998/12/01 01:55:56  fisyak
#  Merge with NT
#
#  Revision 1.6  1998/09/10 22:47:00  fisyak
#  Protection for no sys
#
#  Revision 1.5  1998/09/10 02:00:24  fisyak
#  Add protection for undefined STAR_SYS
#
#  Revision 1.4  1998/06/12 13:12:18  fisyak
#  Fix Linux version
#
#  Revision 1.3  1998/04/24 17:09:08  fisyak
#  Add cray
#
#  Revision 1.2  1998/03/23 02:29:14  fisyak
#  Fix group start-up
#
#  Revision 1.1  1998/03/09 14:29:33  fisyak
#  Switch STAR varibales
#
#  Revision 1.1.1.1  1998/03/09 13:38:24  fisyak
#  Group environment
#
#  Revision 1.2  1998/02/10 00:06:09  fisyak
#  SL98a second version
#
#  Revision 1.1  1998/01/31 23:32:52  fisyak
#  New Environment variables
#
#  Revision 1.2  1998/01/30 12:42:15  fisyak
#  Save changes before moving to SL97b
#
#  Revision 1.1.1.1  1997/12/31 14:35:23  fisyak
#
#             Last modification $Date: 1999/01/08 20:08:27 $ 
#
# Determine STAR_SYS variable.
#
setenv STAR_SYS ""
if (-e /usr/afsws/bin/sys)       setenv STAR_SYS `/usr/afsws/bin/sys`
if ("$STAR_SYS" == "i386_linux2") then
  if (-e /usr/afsws/bin/fs)  then
    if ("`hostname | cut -c1-2`" != "rc") then
      setenv STAR_SYS2 `/usr/afsws/bin/fs sys | awk -F\' '{print $2}'`
      if ("${STAR_SYS2}" == "i386_redhat51")           setenv STAR_SYS ${STAR_SYS2}
      unsetenv STAR_SYS2
    endif
  endif
endif
if (${STAR_SYS} == "") then
set mach_os = ` uname -sr | sed -e 's/ //g' -e 's/\.//g' `
#
switch ($mach_os)
case "sn6*":
	setenv STAR_SYS cray
	breaksw
case "AIX1":
	setenv STAR_SYS rs_aix31
	breaksw
case "AIX2":
	setenv STAR_SYS rs_aix32
	breaksw
case "HP-UXB1020":
	setenv STAR_SYS hp_ux102
	breaksw
case "IRIX4*":
case "IRIX52":
	setenv STAR_SYS sgi_52
	breaksw
case "IRIX53:"
	setenv STAR_SYS sgi_53
	breaksw
case "IRIX62":
	setenv STAR_SYS sgi_62
	breaksw
case "IRIX63":
	setenv STAR_SYS sgi_63
	breaksw
case "IRIX6464":
	setenv STAR_SYS sgi_64
	breaksw
case "Linux*":
	setenv STAR_SYS i386_linux2
	breaksw
case "OSF1V32":
case "OSF1V40":
	setenv STAR_SYS alpha_osf32c
	breaksw
case "OSF1*":
	setenv STAR_SYS osf1
	breaksw
case "SunOS54"
        setenv STAR_SYS sun4x_54
	breaksw
case "SunOS551"
        setenv STAR_SYS sun4x_55
	breaksw
case "SunOS5*":
	switch ("`uname -p`")
	case "*86":
		setenv STAR_SYS sunx86_55
		breaksw
	default:
		setenv STAR_SYS sun4x_55
		breaksw
	endsw
	breaksw
default:
	setenv STAR_SYS unknown
	breaksw
endsw
endif
if ($?STAR_HOST_SYS == 0) setenv STAR_HOST_SYS $STAR_SYS
setenv STAR_SYS      $STAR_SYS
setenv SYS_HOST_STAR $STAR_HOST_SYS
