#!/bin/csh
#  $Log: STAR_SYS,v $
#  Revision 1.25  2000/03/21 02:03:21  fisyak
#  Change default for Linux to i386_redhat61 (LBL request)
#
#  Revision 1.24  2000/03/08 16:06:51  fisyak
#  Leave CC4 as default only for old
#
#  Revision 1.23  2000/02/24 00:24:38  fisyak
#  Keep CC4 default for old/pro and new(for time being)
#
#  Revision 1.21  2000/02/15 23:36:29  fisyak
#  Set CC5 default for Solaris
#
#  Revision 1.20  2000/01/26 17:29:05  fisyak
#  Add arla afs
#
#  Revision 1.19  2000/01/21 23:01:26  fisyak
#  Add RedHat 6.1
#
#  Revision 1.18  1999/11/04 15:36:45  fisyak
#  Add check for /bin/sys for Purdue
#
#  Revision 1.17  1999/10/08 18:12:29  fisyak
#  Take out TEXINPUTS from the list of environment variable, add Linux egcs platform
#
#  Revision 1.16  1999/09/26 21:51:36  fisyak
#  Add non pgf platform for Linux
#
#  Revision 1.15  1999/09/14 17:02:36  fisyak
#  Add redHat 6.0
#
#  Revision 1.14  1999/04/13 20:54:33  fisyak
#  Set all Linuxes to redhat51
#
#  Revision 1.13  1999/03/09 02:03:54  fisyak
#  Add root 2.21.06 for SL99d
#
#  Revision 1.12  1999/03/03 23:45:34  wenaus
#  Add CC5C for compatiblity mode
#
#  Revision 1.11  1999/03/03 23:06:11  fisyak
#  Add CC5 for Sun
#
#  Revision 1.10  1999/01/20 02:18:30  fisyak
#  account fs sysname core dump for rcas/rcrs
#
#  Revision 1.9  1999/01/08 20:57:47  fisyak
#  add i386_linux3
#
#  Revision 1.8  1999/01/08 20:08:27  fisyak
#  Remove call to fs fro rc[as/rs]
#
#  Revision 1.7  1998/12/01 01:55:56  fisyak
#  Merge with NT
#
#  Revision 1.6  1998/09/10 22:47:00  fisyak
#  Protection for no sys
#
#  Revision 1.5  1998/09/10 02:00:24  fisyak
#  Add protection for undefined STAR_SYS
#
#  Revision 1.4  1998/06/12 13:12:18  fisyak
#  Fix Linux version
#
#  Revision 1.3  1998/04/24 17:09:08  fisyak
#  Add cray
#
#  Revision 1.2  1998/03/23 02:29:14  fisyak
#  Fix group start-up
#
#  Revision 1.1  1998/03/09 14:29:33  fisyak
#  Switch STAR varibales
#
#  Revision 1.1.1.1  1998/03/09 13:38:24  fisyak
#  Group environment
#
#  Revision 1.2  1998/02/10 00:06:09  fisyak
#  SL98a second version
#
#  Revision 1.1  1998/01/31 23:32:52  fisyak
#  New Environment variables
#
#  Revision 1.2  1998/01/30 12:42:15  fisyak
#  Save changes before moving to SL97b
#
#  Revision 1.1.1.1  1997/12/31 14:35:23  fisyak
#
#             Last modification $Date: 2000/03/21 02:03:21 $ 
#
# Determine STAR_SYS variable.
#
setenv STAR_SYS ""
if (-e /usr/arla/bin/fs) then
    setenv STAR_SYS `/usr/arla/bin/fs sysname | awk -F\' '{print $2}'`
#    echo $STAR_SYS
else
  if (-e /usr/afsws/bin/fs)  then
#     setenv STAR_SYS `/usr/afsws/bin/sys`
    setenv STAR_SYS `/usr/afsws/bin/fs sysname | awk -F\' '{print $2}'`
  else
    if (-e /bin/sys) setenv STAR_SYS `/bin/sys`
  endif
endif
if ("${STAR_SYS}" == "i386_linux22" || "${STAR_SYS}" == "i386_linux2") then
    set redhat = "5.2";
    setenv STAR_SYS i386_redhat51
    if (-f /etc/redhat-release) set redhat = `awk '{print $5}' /etc/redhat-release`
    if ("$redhat" == "6.0") setenv STAR_SYS "i386_redhat60"
    if ("$redhat" == "6.1") setenv STAR_SYS "i386_redhat61"
endif
if ("$STAR_SYS" == "i386_linux61"|| "$STAR_SYS" == "i386_linux6") setenv STAR_SYS "i386_redhat61"
if ("$STAR_SYS" == "i386_linux22"|| "$STAR_SYS" == "i386_redhat50" || \
    "$STAR_SYS" == "i386_linux2" || "$STAR_SYS" == "i386_linux3") setenv STAR_SYS "i386_redhat51"
if (${STAR_SYS} == "") then
set mach_os = ` uname -sr | sed -e 's/ //g' -e 's/\.//g' `
#
switch ($mach_os)
case "sn6*":
	setenv STAR_SYS cray
	breaksw
case "AIX1":
	setenv STAR_SYS rs_aix31
	breaksw
case "AIX2":
	setenv STAR_SYS rs_aix32
	breaksw
case "HP-UXB1020":
	setenv STAR_SYS hp_ux102
	breaksw
case "IRIX4*":
case "IRIX52":
	setenv STAR_SYS sgi_52
	breaksw
case "IRIX53:"
	setenv STAR_SYS sgi_53
	breaksw
case "IRIX62":
	setenv STAR_SYS sgi_62
	breaksw
case "IRIX63":
	setenv STAR_SYS sgi_63
	breaksw
case "IRIX6464":
	setenv STAR_SYS sgi_64
	breaksw
case "Linux222":
	setenv STAR_SYS i386_redhat51
	breaksw
case "Linux*":
	setenv STAR_SYS i386_redhat61
	breaksw
case "OSF1V32":
case "OSF1V40":
	setenv STAR_SYS alpha_osf32c
	breaksw
case "OSF1*":
	setenv STAR_SYS osf1
	breaksw
case "SunOS54"
        setenv STAR_SYS sun4x_54
	breaksw
case "SunOS551"
        setenv STAR_SYS sun4x_55
	breaksw
case "SunOS5*":
	switch ("`uname -p`")
	case "*86":
		setenv STAR_SYS sunx86_55
		breaksw
	default:
		setenv STAR_SYS sun4x_55
		breaksw
	endsw
	breaksw
default:
	setenv STAR_SYS unknown
	breaksw
endsw
endif
setenv STAR_HOST_SYS $STAR_SYS
if ($?EGCS_ON  == 1 && "${STAR_SYS}" == "i386_redhat51") setenv STAR_HOST_SYS i386_redhat51egcs
if ($?EGCS_ON  == 1 && "${STAR_SYS}" == "i386_redhat60") setenv STAR_HOST_SYS i386_redhat60egcs
if ($?USE_EGCS == 1 && "${STAR_SYS}" == "i386_redhat51") setenv STAR_HOST_SYS i386_redhat51egcs
if ($?USE_EGCS == 1 && "${STAR_SYS}" == "i386_redhat60") setenv STAR_HOST_SYS i386_redhat60egcs
if ($?USE_KCC  == 1 && "${STAR_SYS}" == "i386_redhat60") setenv STAR_HOST_SYS i386_redhat60kcc
if ("${STAR_SYS}" == "sun4x_56") then
    if ($STAR_LEVEL  == "old") then
	if ($?USE_CC4  == 1 && $?USE_CC5  == 1) unsetenv USE_CC5
	if ($?USE_CC5  == 0 && "${STAR_SYS}" == "sun4x_56") setenv USE_CC4 "YES"
    else
	if ($?USE_CC4  == 1 && $?USE_CC5  == 1) unsetenv USE_CC4
	if ($?USE_CC4  == 0 && "${STAR_SYS}" == "sun4x_56") setenv USE_CC5 "YES"
    endif
    if ($?USE_CC5  == 1) setenv STAR_HOST_SYS sun4x_56_CC5
endif
