#!/usr/bin/env perl

#
# Deletes all files with available <= 0 or sanity <= 0
# Attention: this will work for a give storage
#
# Written J. Lauret - 2002 - 2006
#
# DO NOT change the arguments please
#
# Usage:
#   % ./$0 localhost NFS
#   % ./$0 rcas6001.rcf.bnl.gov
#
#

use lib "/afs/rhic.bnl.gov/star/packages/scripts";
use FileCatalog;

my $hostName;

$OK = 1;

if ( defined($ARGV[0]) ){
    $hostName = $ARGV[0];

    my $fC = FileCatalog->new();
    if ( $fC ){
	$fC->connect_as("User");

        # those are sign that the files
	# where marked for deletion
	foreach $select ("available<0","sanity<=0"){
	    $start =   0;
	    $limit = 500;
	    $fC->clear_context();
	    $fC->set_delimeter("/");

	    do {
		$fC->set_context("startrecord=$start",
				 "limit=$limit",
				 "node=$hostName",
				 defined($ARGV[1])?"storage=$ARGV[1]":"storage=local",
				 "nounique=1",
				 $select
				 );
		@all = $fC->run_query("path","filename");
		if ($#all != -1){
		    foreach $ff (@all){
			if ( -e $ff ){
			    push(@ALL,$ff);
			#} else {
			#    print localtime()." $ff not found\n";
			}
		    }
		}
		$start += $limit;
	    } while ($#all  == ($limit-1));
	}

	# No perform the operation
	if ($#ALL != -1){
	    foreach $file (@ALL){
		if ( -e $file ){
		    # still needs to check
		    if ($OK){
			if ( unlink($file) ){
			    print localtime()." $file deleted\n";
			}
		    } else {
			print "/bin/rm -f $file\n";
		    }
		}
	    }
	}
	1;

    } else {
	0;
    }

} else {
    0;
}

